# flagos op backend config
# Format: op_name = backend
# backend: flaggems | cuda
# Default (unlisted ops): flaggems
#
# Override config path: FLAGOS_BACKEND_CONFIG=/path/to/backends.conf

mm = flaggems
mm.out = flaggems
bmm = flaggems
bmm.out = flaggems
# cat = flaggems
cat = cuda
embedding = flaggems
add.Tensor = cuda
mul.Tensor = cuda
silu = cuda
rsqrt = cuda
mean.dim = cuda
cos = cuda
sin = cuda
neg = cuda
pow.Tensor_Scalar = cuda
all = cuda
_softmax = flaggems
bitwise_and.Tensor = cuda
le.Tensor = cuda
where.self = cuda
index.Tensor = cuda
new_ones = cuda
scalar_tensor = cuda
