#!/usr/bin/env python3
"""
Codegen for torch_fl Ascend (aclnn) operators.

Unlike the CUDA codegen (scripts/codegen_ops.py), which emits a one-line
`at::op(args)` boxing body and relies on the dedicated CUDA dispatch key,
Ascend has no independent key to box into (torch_npu shares PrivateUse1 with
flagos). So every Ascend kernel must call CANN aclnn (libopapi.so) directly.

Because the aclnn call shape is uniform per *category*, this generator is
category-driven: a mapping table classifies each op, and a per-category
template emits the argument marshalling + output allocation + EXEC_ASCEND_CMD.

This round implements ONLY the `unary` category:
    1 Tensor in -> 1 Tensor out, same shape/dtype, body:
        aclnn<Name>(self, out)

Reuses:
  - scripts/codegen_ops.py:schema_to_cpp_name  (symbol names must match the
    dispatcher declarations already emitted into generated/ops.h)
  - the dispatchers/DECLARE_DISPATCHER already present in generated/ops.h
    (we only add the Backend::kAscend slot; we declare nothing new)

Generates:
  - csrc/aten/backends/ascend/generated/ascend_kernels.cc
  - appends newly-covered ops to torch_fl/backends_ascend.conf

Validation:
  - each derived aclnn<Name>/<Name>GetWorkspaceSize symbol must exist in
    libopapi.so, else the op is skipped with a warning.
  - handwritten ops (SKIP set) are never re-emitted (would double-register
    kAscend and crash at import).
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path

# Reuse the authoritative symbol-naming from the CUDA codegen so the emitted
# REGISTER_IMPL_TO_DISPATCHER(FnType, dispatcher, ...) matches the
# DECLARE_DISPATCHER in generated/ops.h exactly (else the build won't link).
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from codegen_ops import schema_to_cpp_name  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
OUT_CC = REPO / "csrc/aten/backends/ascend/generated/ascend_kernels.cc"
CONF = REPO / "torch_fl/backends_ascend.conf"

# --------------------------------------------------------------------------
# Category mapping table.
#
# For `unary`: aten schema op name -> optional aclnn-name override.
# Default aclnn name = "aclnn" + PascalCase(op base). An explicit string
# overrides the PascalCase stem (e.g. some ops have irregular aclnn spelling).
#
# Ops already handwritten in csrc/aten/backends/ascend/*.cc are in SKIP and
# must NOT appear here (they already own the kAscend slot).
# --------------------------------------------------------------------------
UNARY_OPS = {
    "sqrt": None,
    "exp": None,
    "tanh": None,
    "sigmoid": None,
    "reciprocal": None,
    "log": None,
    "floor": None,
    "ceil": None,
}

# Ops with a handwritten kAscend kernel — never regenerate (double-register).
SKIP = {
    "abs", "acos", "cos", "sin", "neg", "rsqrt", "silu",
}


def aclnn_name(op_base: str, override) -> str:
    if override:
        return "aclnn" + override
    pascal = "".join(w.capitalize() for w in op_base.split("_") if w)
    return "aclnn" + pascal


def libopapi_path() -> Path:
    ah = os.environ.get("ASCEND_HOME", "/usr/local/Ascend/ascend-toolkit/latest")
    return Path(ah) / "lib64" / "libopapi.so"


def symbols(lib: Path) -> set:
    if not lib.exists():
        print(f"[warn] {lib} not found; skipping symbol validation", file=sys.stderr)
        return None
    out = subprocess.run(["nm", "-D", str(lib)], capture_output=True, text=True)
    syms = set()
    for line in out.stdout.splitlines():
        parts = line.split()
        if parts:
            syms.add(parts[-1])
    return syms


UNARY_KERNEL_TMPL = """\
at::Tensor {kernel}(const at::Tensor& self) {{
  namespace ascend = at::native::flagos::ascend;
  auto out = ascend::OpPreparation::apply_tensor_without_format(
      self.sizes(), self.options());

  ascend::AclTensorWrapper acl_self(self);
  ascend::AclTensorWrapper acl_out(out);

  EXEC_ASCEND_CMD({aclnn}, acl_self.get(), acl_out.get());
  return out;
}}

REGISTER_IMPL_TO_DISPATCHER({fn}, {disp}, Backend::kAscend, {kernel})
"""

FILE_HEADER = """\
// Copyright (c) 2026, BAAI. All rights reserved.
//
// @generated by scripts/codegen_ascend.py -- DO NOT EDIT.
//
// aclnn kernels for the Ascend backend, generated per-category. Each kernel
// marshals aten tensors into aclTensors and issues the two-phase aclnn call
// via EXEC_ASCEND_CMD. Dispatchers are declared in generated/ops.h (shared
// with the CUDA codegen); here we only fill the Backend::kAscend slot.

#include "../../../generated/ops.h"
#include <ATen/core/Tensor.h>
#include "../op_preparation.h"
#include "../op_api_common.h"

namespace at::native::flagos {

"""

FILE_FOOTER = "\n} // namespace at::native::flagos\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--category", default="unary", choices=["unary"],
                    help="which category to generate (only 'unary' implemented)")
    ap.add_argument("--no-conf", action="store_true",
                    help="do not append covered ops to backends_ascend.conf")
    args = ap.parse_args()

    syms = symbols(libopapi_path())

    bodies = []
    covered = []
    skipped = []
    for op, override in UNARY_OPS.items():
        if op in SKIP:
            skipped.append((op, "handwritten"))
            continue
        acl = aclnn_name(op, override)
        if syms is not None:
            if (acl not in syms) or (acl + "GetWorkspaceSize" not in syms):
                skipped.append((op, f"{acl} not in libopapi.so"))
                continue
        fn, disp = schema_to_cpp_name(op)
        kernel = fn[:-2] + "KernelAscend"  # SqrtFn -> SqrtKernelAscend
        bodies.append(UNARY_KERNEL_TMPL.format(
            kernel=kernel, aclnn=acl, fn=fn, disp=disp))
        covered.append(op)

    OUT_CC.parent.mkdir(parents=True, exist_ok=True)
    OUT_CC.write_text(FILE_HEADER + "\n".join(bodies) + FILE_FOOTER)
    print(f"[gen] {OUT_CC.relative_to(REPO)}  ({len(covered)} kernels)")
    for op in covered:
        print(f"       + {op} -> {aclnn_name(op, UNARY_OPS[op])}")
    for op, why in skipped:
        print(f"       - {op} skipped ({why})")

    if not args.no_conf and covered:
        existing = CONF.read_text() if CONF.exists() else ""
        lines = []
        for op in covered:
            if f"\n{op} = " not in ("\n" + existing):
                lines.append(f"{op} = ascend")
        if lines:
            with CONF.open("a") as f:
                f.write("\n# --- generated by codegen_ascend.py (unary) ---\n")
                f.write("\n".join(lines) + "\n")
            print(f"[conf] appended {len(lines)} op(s) to {CONF.relative_to(REPO)}")


if __name__ == "__main__":
    main()
